stages:
  - build
  - test
  - deploy


variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 02:00:00"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "push"'
      when: always

dev-build:
  stage: build
  only: 
    - dev
  tags: [cori]
  script:
    - bash conda/build-nersc.sh

dev-test:
  stage: test
  only:
    - dev
  tags: [cori]
  script: 
    -  bash ci/test-descqa-nersc.bash 1
    
dev-deploy:
  stage: deploy
  only:
    - dev
  tags: [cori]
  script:
    - bash conda/set-symlinks.sh dev
    
#release-test:
#  stage: test
##  rules: 
#    - if: '$CI_COMMIT_TAG'
#  tags: [cori]
#  script: 
#    - bash ci/test-descqa-nersc.bash 1
    


main-build:
  stage: build
  only: 
    - main
  except: 
    variables:
      - $CI_COMMIT_TAG
  tags: [cori]
  script:
    - bash conda/build-nersc.sh 1

main-test:
  stage: test
  only:
    - main
  except: 
    variables:
      - $CI_COMMIT_TAG
  tags: [cori]
  script: 
    -  bash conda/test-nersc.sh 1
    
main-deploy:
  stage: deploy
  only:
    - main
  except: 
    variables:
      - $CI_COMMIT_TAG
  tags: [cori]
  script:
    - bash conda/set-symlinks.sh prod


#main-test:
#  stage: test
#  only:
#    - main
#  except: 
#    variables:
##      - $CI_COMMIT_TAG
#  tags: [cori]
#  script: 
#    - bash ci/test-descqa-nersc.bash 1






