stages:
  - test


variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 01:00:00"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule"'
      when: always
  

release-test:
  stage: test
  rules: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script: 
    - bash ci/test-descqa-nersc.bash 1
    
    
main-test:
  stage: test
  only:
    - main
  except: 
    variables:
      - $CI_COMMIT_TAG
  tags: [cori]
  script: 
    - bash ci/test-descqa-nersc.bash 1






