name: base
channels:
  - conda-forge/label/mpi-external
  - conda-forge
platforms:
  - linux-64
  - osx-64
dependencies:
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - astroplan
  - astropy
  - bokeh
  - camb
  - clmm
  - cmake
  - cmasher
  - compilers
  - corner
  - dask
  - dask-jobqueue
  - dask-mpi
  - dask-sql
  - datashader
  - diffsky
  - dm-tree
  - dust_extinction
  - dustmaps
  - eigen
  - emcee
  - fast3tree
  - fast-pt
  - fastparquet
  - firecrown
  - fitsio=1.2.6
  - flake8
  - galsim
  - gcr
  - globus-sdk
  - google-cloud-bigquery
  - graphviz
  - gsl
  - h5py[build=mpi*]
  - hdf5[build=mpi*]
  - healpy
  - healsparse
  - holoviews
  - ipympl
  - jax
  - jaxlib
  - jupyter
  - lsstdesc-ceci
  - lsstdesc-coord
  - lsstdesc-gcr-catalogs
  - markupsafe
  - matplotlib
  - mockmpi
  - mpi4py
  - mpich
  - namaster
  - nbconvert
  - ndcctools
  - nose
  - numba
  - numdifftools
  - numpy
  - numpydoc
  - opencosmo
  - pandas
  - parallel_statistics
  - parsl
  - pip
  - pot
  - psutil
  - psycopg2
  - pyarrow
  - pybind11
  - pyccl
  - pygraphviz
  - pymssql
  - pytables
  - pytest
  - python-snappy
  - pyvo
  - qp-prob
  - redmapper
  - sacc
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - snappy
  - somoclu
  - sphinx
  - sqlalchemy
  - starlink-ast
  - tables-io-full
  - tabulate
  - threadpoolctl
  - tjpcov
  - treecorr
  - yaml
  - pip:
    - ceci
    - fits2hdf
    - glass
    - git+https://github.com/beckermr/hybrideb@a3198ea5bc8175542b058e5c1289d910f05fd99d
    - git+https://github.com/jlvdb/hyperbolic@b88b107a291fa16c2006cf971ce610248d58e94c
    - lsstdesc-dataregistry
    - pz-rail[algos]>=1.2.3
