name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - astroplan
  - astropy
  - bokeh
  - camb
  - cmake
  - cmasher
  - compilers
  - corner
  - dask
  - dask-jobqueue
  - dask-mpi
  - dask-sql
  - datashader
  - dust_extinction
  - dustmaps
  - eigen
  - emcee
  - fast3tree
  - fast-pt
  - fastparquet
  - firecrown
  - fitsio=1.2.6
  - flake8
  - galsim
  - gcr
  - google-cloud-bigquery
  - graphviz
  - gsl
  - h5py[build=mpi*]
  - hdf5[build=mpi*]
  - healpy
  - healsparse
  - holoviews
  - ipympl
  - jax
  - jaxlib
  - jupyter
  - lsstdesc-coord
  - lsstdesc-diffsky
  - lsstdesc-gcr-catalogs
  - markupsafe
  - matplotlib
  - mpi4py
  - mpich===4.2.2[build=external_*]
  - namaster
  - ndcctools
  - nose
  - numba
  - numdifftools
  - numpy
  - numpydoc
  - pandas
  - parallel_statistics
  - parsl
  - pip
  - pot
  - psycopg2
  - pyarrow
  - pybind11
  - pyccl
  - pymssql
  - pytables
  - pytest
  - python-snappy
  - pyvo
  - redmapper
  - sacc
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - selenium
  - snappy
  - somoclu
  - sphinx
  - sqlalchemy
  - starlink-ast
  - tabulate
  - treecorr
  - yaml
  - pip:
    - ceci
    - fits2hdf
    - lsstdesc-dataregistry
    - nvidia-nccl-cu12==2.27.7
    - pz-rail[algos]>=1.2.3
