name: desc-python create ci version

on: 
 # push:
 #   branches:
 #     - master
  workflow_dispatch:
 # schedule:
 #   - cron: '45 20 * * 0'
    
env:
  TEST_TAG: lsstdesc/desc-python:ci-dev


jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: heather999
          password: '${{ secrets.DOCKERHUB_ACCESSTOK }}'      
      
      - name: checkout desc-python
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: setup VM python to install docker-squash
        uses: actions/setup-python@v4
        with:
        python-version: '3.x'
        
      - name: Install pip and docker-squash.
        run: |
          python -m pip install --upgrade pip
          python -m pip install docker-squash
     
      - name : Get date 
        run: |
          echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV 
          echo $GITHUB_WORKSPACE
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

  #    - name: pull old build
  #      run: |
  #       docker pull lsstdesc/desc-python:ci
  #       docker tag lsstdesc/desc-python:ci lsstdesc/desc-python:ci-old
  #       docker push lsstdesc/desc-python:ci-old
        
      - name: Build 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            GH_SHA=${{ github.sha }}
          push: true
          tags: ${{ env.TEST_TAG }}

   
      - name: test image before pushing
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py37/etc/profile.d/conda.sh && conda activate base && python -c 'import astropy'"
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py38/etc/profile.d/conda.sh && conda activate base && python -c 'import astropy'"
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py39/etc/profile.d/conda.sh && conda activate base && python -c 'import astropy'"
          docker tag ${{ env.TEST_TAG }} lsstdesc/desc-python:ci-${{env.DATE_TAG}}
          docker-squash -t lsstdesc/desc-python:ci-${{env.DATE_TAG}} 
          docker push lsstdesc/desc-python:ci-${{env.DATE_TAG}} ${{ env.TEST_TAG }}
          docker tag lsstdesc/desc-python:ci-${{env.DATE_TAG}} lsstdesc/desc-python:ci
          docker push lsstdesc/desc-python:ci
       
       
