name: desc-python bleed new

on: 
  workflow_dispatch:

env:
  TEST_TAG: lsstdesc/desc-python:bleed-dev


jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: heather999
          password: '${{ secrets.DOCKERHUB_ACCESSTOK }}'      
      
      - name: checkout desc-python
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: bleed
     
      - name : Get date 
        run: |
          echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV 
          echo $GITHUB_WORKSPACE
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

        
      - name: Build 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GH_SHA=${{ github.sha }}
          push: true
          tags: ${{ env.TEST_TAG }}

   
      - name: test image before pushing
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py/etc/profile.d/conda.sh && conda activate base && python -c 'import astropy'"
          docker tag ${{ env.TEST_TAG }} lsstdesc/desc-python:bleed-${{env.DATE_TAG}}
          docker push lsstdesc/desc-python:bleed-${{env.DATE_TAG}}
          docker tag ${{ env.TEST_TAG }} lsstdesc/desc-python:bleed-dev
          docker push lsstdesc/desc-python:bleed-dev
       
       
