name: desc-python bleed branch

on: 
  push:
    branches:
      - bleed
 
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-python
        uses: actions/checkout@v2
        with:
          ref: bleed
      - name: do fresh docker build
        run: docker build --no-cache -t lsstdesc/desc-python:bleed -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push
        run: docker push lsstdesc/desc-python:bleed
