name: desc-python-test

on:
#  pull_request:
#    branches: 
#      - master
  workflow_dispatch:


jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-python
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: issue/96/fix-latest
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/desc-python:latest -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Test desc-python 
        run: docker run --rm lsstdesc/desc-python:latest /bin/bash -c "source /opt/desc/py/etc/profile.d/conda.sh && conda activate desc && python -c 'import pyccl'"
      - name: Docker push
        run: docker push lsstdesc/desc-python:latest
