name: desc-python prod-tag

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-python
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pull latest build
        run: docker pull lsstdesc/desc-python:dev
      - name: tag dev build as prod
        run: docker tag lsstdesc/desc-python:dev lsstdesc/desc-python:prod
      - name: push prod
        run: docker push lsstdesc/desc-python:prod

