name: desc-python latest

on:
#  push:
#    branches: 
#      - master
#  pull_request:
#    branches:
#      - master
  workflow_dispatch:
  
env:
  TEST_TAG: lsstdesc/desc-python:latest-dev


jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: heather999
          password: '${{ secrets.DOCKERHUB_ACCESSTOK }}'      
      
      - name: checkout desc-python
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
          
      - name : Get date 
        run: |
          echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV 
          echo $GITHUB_WORKSPACE
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Build 
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}
          
          
      - name: test image before pushing
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py/etc/profile.d/conda.sh && conda activate base && python -c 'import astropy'"
          docker tag ${{ env.TEST_TAG }} lsstdesc/desc-python:latest-{{env.DATE_TAG}}
          docker push lsstdesc/desc-python:latest-${{env.DATE_TAG}}
          docker tag ${{ env.TEST_TAG }} lsstdesc/desc-python:latest
          docker push lsstdesc/desc-python:latest
       
